before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: s1/vID8xLbmS9eamqbHjyoH+2iJX8cK1CrzV3CRXTXmRH83l6tt4uuKmCN8jnglo7683mOpBN0E7ubdmTuqhU1+ynxKEmVAGrBRcY/CG6wC86SVAMZa+ZQ35cu7xNQXrKkNh8MMVJNDQeYBJCGTrtIbg+kWA/z700Wkcy+TDxXQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: NzUxMTMzZWViMDU0OTZjMDAwNTkxZDRmYzZhYmFhMmU=N8t/K2IynowLnoRWgyDgndF3e7sbQs+Y+kl1szw2aRxb2ICW454NVuxvGyUp727X0KEDcQibl8eP69I8e3NILYomLB5D1A6VS3yl46hxO4/ZRHECI4Op70crnnDdYwDZhJfWFNkCeA51Sp4a2WtxRUj4CWtACzIx8bGfOlxYc6M3TB2Ou/ElgW3ZggUFbyzvAjXhe1nPlt+10/ic4qiN9qNW1qUySg0qsPtt6fHplfV4AQWuSdgEcGYD3A8XgnQYcgvH/SK/GiiRdVpghnYZf/wMeEyE0NMylhMZ1aEnAT1t2uI3gX+NllVFrjYRZUSR7SlhOjJGPl2PP3m3+y6rpmjy0KHaQcyzxOzUnxuAfC87eSGcHJl7OxfgRUg2YkZdTdNTRPyMAi1YjzZcpzVpRTxcNFv2xrd2hGhm/oYCa5Vm0ZgzXvuZnqo390rnycOTgwsiBMOhJdltIqpB+uIFUdizexxplEpxb7Zf/PWemaIEVg/Yk3W0aLapg3wknpmIPHsCkjz0+sHsIRT+KSQbz/IRghZxS5sPHaklAnDwzcW5Q2bTiSNpn1FU3HPJB6nx1pGkx70Q1IbDl1mMPEMHfupWJPA3kRBjJYu/TjjPB1E3vgAzBtTXqvZN3t9e7qHSfaKEcz4wSGTKMpX6nzLpLxVdTQOM3I6cllWZPzd/oEKSRrborqQZSDB9JRwczaiERn5rfaRouplc4S1dkKs5laInCfohG+u9ybFmzJfKTETjn5lwIjRQa2+t2tgT2cfnrgweMS7nEMV83Wx5vpGExjtkYNwam2XlZw2ftTZSdM60SZAhhybBeTJG7opavdwFD2WST5LYKQzYyGJXvD55pKr9WIrMUu5Swq22cbOt/EjC5zliKwOE9yjziydrhk0b7aTNINfJv/7lwkaQu98ap3kLyz5o63Z3GTDNLl8VtlMEA4rlYznYh3tazq3c46S3rOScOWo97o70sl6bIKWzewbus+qmZSVePEImv0MpapqeFUUbGXWzP/ErK+RuYa67f2/yZ5968f1ziYoBIvP1kFTkvaQz8jckEH0E1b9dk2e23D0YfFgx1/AHui7JRLiS6kxRkqVVyc5+SdBTan60XeY3gHj6iEkjp12oNsDiHZ7N8m+sn8wi/mcxYqMDs1dC9stcY2FMxGYEtyazAUdDi8/bFIu9cHPO0DQLlmcCr3+QfAa8EA1FkYmjtzmEsWiJlkjJlthTrb9ZtzLvfLnvvLhRiZZ6HeHhVQFvY8X3ede87o11F0JkM4R4rwYYWg7rlnSE5bTU8+8B2a6AZkh4I89+izp+CRyLhRJrDXJHIyjFGrTeAbfzNdYNwXYhb0+ikye8JzGx+usR57NcdQzJL+flj+n4Sco1n6fFWoI+Lx7XYASuJ+bDYS+vl0dQRSTZUG7llmnbmoI2goyVPlVpmO/Lh8AIVurfO6/Ue2kczqlPs/tUaIveG82Kwd+XRrlzZO7B/ovEV+8WiuVbj+929yKhqSbPB9/se/geC0j3TaDKN5F44mVM3Tkxl82/jWa1KUyq9cnykbnq/ondEylEVKX1BE5B5spwTiZH4PfYZku3YLmDu8ebyuSRBVEiUVZK # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
